services:
  mysqldb:
    platform: linux/x86_64
    image: mysql:8.0.33
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQLDB_DATABASE}
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 30s
      retries: 3
  app:
    platform: linux/x86_64
    depends_on:
      - mysqldb
    restart: on-failure
    image: springproject
    build: .
    env_file: ./.env
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
      - ${DEBUG_PORT}:${DEBUG_PORT}
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:${MYSQLDB_DOCKER_PORT}/${MYSQLDB_DATABASE}?serverTimeZone=UTC&createDatabaseIfNotExist=true",
        "spring.datasource.username": "${MYSQLDB_USER}",
        "spring.datasource.password": "${MYSQLDB_ROOT_PASSWORD}",
        "spring.datasource.driver-class-name" : "${SPRING_DATASOURCE_DRIVER_CLASS_NAME}",
        "server.servlet.context-path": "${SERVER_SERVLET_CONTEXT_PATH}"
      }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:${DEBUG_PORT}"